[alias]
b = "build"
c = "check"
t = "test"
r = "run"
rr = "run --release"
n = "new"

[build]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]
