[general]
seperator = " | "

[aliases]
"firefox" = "Firefox"
"discord" = "Discord"
"org.wezfurlong.wezterm" = "Wezterm"
"ptolemy-vergil-VergilApplication" = "Ptolemy 2"
"DB Browser for SQLite" = "SQLite Browser"

[options]
remove_duplicates = true
